// ABMNZN SDK 2014-02-12-k8c52wxs
if (window.amazon == null || window.amazon.Login == null) {
(function() {
'use strict';var f=void 0,g=!0,h=null,i=!1;function k(a){return function(){return this[a]}}var m,n,q,r,s,u;function aa(a,b){if(a===h||a===f)a={};for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d!==h&&d!==f)for(var e in d)a[e]=d[e]}return a}function v(a,b){var c=w.apply(f,arguments),d=c;window.console&&window.console.log&&("function"==typeof d&&(d=d()),d=w("[Amazon.%s] %s","error",d),window.console.log(d));throw Error(c);}
function w(a,b){var c=arguments,d=1;return a.replace(/%((%)|[sid])/g,function(a){if(a[2])return a[2];a=c[d++];"object"==typeof a&&(window.JSON&&window.JSON.stringify)&&(a=window.JSON.stringify(a));return a})}function x(a,b,c){b==h&&v("missing %s",a);typeof b!=c&&v("expected %s to be a %s",a,c)}
function ba(a){var b=document.getElementById(a);b||(b=document.createElement("div"),b.setAttribute("id",a),b.setAttribute("width",0),b.setAttribute("height",0),b.setAttribute("style","position: absolute; left: -1000px; top: -1000px"),b.style.setAttribute&&b.style.setAttribute("cssText","position: absolute; left: -1000px; top: -1000px"),a=document.getElementById("amazon-root"),a||(a=document.createElement("div"),a.setAttribute("id","amazon-root"),document.body.appendChild(a)),a.appendChild(b));return b}
function ca(){this.a=[]}ca.prototype.b=function(a){var b=this.a;this.a=[];for(var c=0;c<b.length;c++)b[c].u&&this.a.push(b[c]);for(c=0;c<b.length;c++)b[c].q.apply(f,arguments)};var da,y,A,ea={'"':'"',"\\":"\\","/":"/",K:"\b",L:"\f",M:"\n",N:"\r",O:"\t"},fa;function B(a){throw{name:"SyntaxError",message:a,J:y,text:fa};}function C(a){a&&a!==A&&B("Expected '"+a+"' instead of '"+A+"'");A=fa.charAt(y);y+=1;return A}
function ga(){var a;a="";"-"===A&&(a="-",C("-"));for(;"0"<=A&&"9">=A;)a+=A,C();if("."===A)for(a+=".";C()&&"0"<=A&&"9">=A;)a+=A;if("e"===A||"E"===A){a+=A;C();if("-"===A||"+"===A)a+=A,C();for(;"0"<=A&&"9">=A;)a+=A,C()}a=+a;if(isFinite(a))return a;B("Bad number")}
function ha(){var a,b,c="",d;if('"'===A)for(;C();){if('"'===A)return C(),c;if("\\"===A)if(C(),"u"===A){for(b=d=0;4>b;b+=1){a=parseInt(C(),16);if(!isFinite(a))break;d=16*d+a}c+=String.fromCharCode(d)}else if("string"===typeof ea[A])c+=ea[A];else break;else c+=A}B("Bad string")}function D(){for(;A&&" ">=A;)C()}
function ia(){switch(A){case "t":return C("t"),C("r"),C("u"),C("e"),g;case "f":return C("f"),C("a"),C("l"),C("s"),C("e"),i;case "n":return C("n"),C("u"),C("l"),C("l"),h}B("Unexpected '"+A+"'")}var E;
E=function(){D();switch(A){case "{":var a;a:{var b={};if("{"===A){C("{");D();if("}"===A){C("}");a=b;break a}for(;A;){a=ha();D();C(":");Object.hasOwnProperty.call(b,a)&&B('Duplicate key "'+a+'"');b[a]=E();D();if("}"===A){C("}");a=b;break a}C(",");D()}}B("Bad object");a=f}return a;case "[":a:{a=[];if("["===A){C("[");D();if("]"===A){C("]");break a}for(;A;){a.push(E());D();if("]"===A){C("]");break a}C(",");D()}}B("Bad array");a=f}return a;case '"':return ha();case "-":return ga();default:return"0"<=A&&
"9">=A?ga():ia()}};da=function(a,b){var c;fa=a;y=0;A=" ";c=E();D();A&&B("Syntax error");return"function"===typeof b?function e(a,c){var l,j,z=a[c];if(z&&"object"===typeof z)for(l in z)Object.prototype.hasOwnProperty.call(z,l)&&(j=e(z,l),j!==f?z[l]=j:delete z[l]);return b.call(a,c,z)}({"":c},""):c};var ja;function F(a){return 10>a?"0"+a:a}
function ka(a){la.lastIndex=0;return la.test(a)?'"'+a.replace(la,function(a){var c=ma[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}
function G(a,b){var c,d,e,p,t=H,l,j=b[a];j&&("object"===typeof j&&"function"===typeof j.toJSON)&&(j=j.toJSON(a));"function"===typeof I&&(j=I.call(b,a,j));switch(typeof j){case "string":return ka(j);case "number":return isFinite(j)?String(j):"null";case "boolean":case "null":return String(j);case "object":if(!j)return"null";H+=J;l=[];if("[object Array]"===Object.prototype.toString.apply(j)){p=j.length;for(c=0;c<p;c+=1)l[c]=G(c,j)||"null";e=0===l.length?"[]":H?"[\n"+H+l.join(",\n"+H)+"\n"+t+"]":"["+
l.join(",")+"]";H=t;return e}if(I&&"object"===typeof I){p=I.length;for(c=0;c<p;c+=1)"string"===typeof I[c]&&(d=I[c],(e=G(d,j))&&l.push(ka(d)+(H?": ":":")+e))}else for(d in j)Object.prototype.hasOwnProperty.call(j,d)&&(e=G(d,j))&&l.push(ka(d)+(H?": ":":")+e);e=0===l.length?"{}":H?"{\n"+H+l.join(",\n"+H)+"\n"+t+"}":"{"+l.join(",")+"}";H=t;return e}}
"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+F(this.getUTCMonth()+1)+"-"+F(this.getUTCDate())+"T"+F(this.getUTCHours())+":"+F(this.getUTCMinutes())+":"+F(this.getUTCSeconds())+"Z":h},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});
var la=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,H,J,ma={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},I;ja=function(a,b,c){var d;J=H="";if("number"===typeof c)for(d=0;d<c;d+=1)J+=" ";else"string"===typeof c&&(J=c);if((I=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return G("",{"":a})};
function K(a){var b="",c;for(c in a)b&&(b+="&"),b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c]+"");return b}function na(a,b){for(var c=0;c<b.length;c++){var d=b[c];""!=d&&!a.b.hasOwnProperty(d)&&(a.a.push(d),a.b[d]=1)}}n=function(a){this.a=[];a="string"==typeof a?a.split(/\s+/):a;this.b={};na(this,a)};n.prototype.contains=function(a){for(var b=0;b<a.a.length;b++)if(!this.b.hasOwnProperty(a.a[b]))return i;return g};n.prototype.add=function(a){na(this,a.a)};n.prototype.toString=function(){return this.a.join(" ")};
q={};var oa=h;q.s=function(){return oa};q.n=function(a){x("domain",a,"string");var a=a.replace(/^\s+|\s+$/g,""),b="."+window.location.hostname;"."!=a.charAt(0)&&(a="."+a);b.indexOf(a)!=b.length-a.length&&v("Site domain must contain the current page's domain");oa=a};q.j=function(){};q.j.prototype.getItem=function(){};q.j.setItem=function(){};q.j.removeItem=function(){};function L(){}
L.prototype.getItem=function(a){a=RegExp("(?:^|;)\\s*"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*)(?:;|$)").exec(document.cookie);return a==h?h:unescape(a[1])};L.prototype.setItem=function(a,b,c){var c=c==h?"Fri, 31 Dec 9999 23:59:59 GMT":(new Date((new Date).getTime()+1E3*c)).toGMTString(),d=q.s(),d=d==h?"":";Domain="+d,e=pa(M(window.location.href+""))?"":";Secure";document.cookie=a+"="+escape(b)+";Expires="+c+d+";Path=/"+e};
L.prototype.removeItem=function(a){q.d.setItem(a,"null",0)};q.d=new L;function N(a){this.a=a}N.prototype.getItem=function(a){return this.a.getItem(a)};N.prototype.setItem=function(a,b,c){this.a.setItem(a,b,c)};N.prototype.removeItem=function(a){q.d.removeItem(a)};q.i=new N(q.d);
r={B:function(a,b){if("bearer"==a.token_type){var c=ja({access_token:a.access_token,max_age:b,expiration_date:(new Date).getTime()+1E3*b,client_id:s.r(),scope:a.scope});q.i.setItem("amazon_Login_state_cache",c,b)}},C:function(){var a=q.i.getItem("amazon_Login_state_cache");return a!=h&&(a=da(a),a!=h&&a.expiration_date>(new Date).getTime())?(a.scope=new n(a.scope),a):h},k:function(){q.i.removeItem("amazon_Login_state_cache")}};
function O(a,b,c,d,e,p){this.a=new P(a,b,c);("string"!=typeof d||!d)&&v("missing or invalid path: %s",d);this.e=d;"object"==typeof e&&(e=K(e));e&&"string"!=typeof e&&v("invalid query: %s",e);this.c=e||"";"object"==typeof p&&(p=K(p));p&&"string"!=typeof p&&v("invalid fragment: %s",p);this.b=p||""}
function M(a){var b=document.createElement("div");b.innerHTML="<a></a>";b.firstChild.href=a;b.innerHTML=b.innerHTML;a=b.firstChild;""==a.host&&(a.href=a.href);b=a.port;if(!b||"0"==b)b=h;var c=a.pathname;c?"/"!=c[0]&&(c="/"+c):c="/";return new O(a.protocol,a.hostname,b,c,a.search.substring(1),a.href.split("#")[1]||"")}m=O.prototype;m.scheme=function(){return this.a.scheme()};m.host=function(){return this.a.host()};m.port=function(){return this.a.port()};m.path=k("e");m.f=k("c");m.g=k("b");
function pa(a){var b="http"==a.a.scheme(),a=a.a.host();return b&&("localhost"==a||"127.0.0.1"==a)}m.toString=function(){var a=this.a.toString(),a=a+this.e,a=a+(this.c?"?"+this.c:"");return a+=this.b?"#"+this.b:""};function qa(a,b){return new O(b.scheme!==f?b.scheme:a.scheme(),b.host!==f?b.host:a.host(),b.port!==f?b.port:a.port(),b.path!==f?b.path:a.path(),b.f!==f?b.f:a.f(),b.g!==f?b.g:a.g())}
function P(a,b,c){var d;("string"!=typeof a||!(d=a.match(/^(https?)(:(\/\/)?)?$/i)))&&v("missing or invalid scheme: %s",a);this.a="http"==d[1]?"http":"https";("string"!=typeof b||!b.match(/^[\w\.\-]+$/))&&v("missing or invalid host: %s",b);this.c=b;if(c&&((c+"").match(/^\d+$/)||v("invalid port: %s",c),80==c&&"http"==this.a||443==c&&"https"==this.a))c=h;this.b=c?c+"":h}var ra=/^(http|https):\/\/([a-z0-9\-\.]+)(:(\d+))?$/i;P.prototype.scheme=k("a");P.prototype.host=k("c");P.prototype.port=k("b");
P.prototype.toString=function(){var a;a=""+(this.a+"://");a+=this.c;return a+=this.b?":"+this.b:""};function Q(a,b,c,d){return new O(a.a,a.c,a.b,b,c,d)}function sa(a){for(var b="",c=0;c<a;c++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return b}var R={},S=h;
function ta(a){var b=T;a:if(window.__toucanForceProxyOriginTo){var b=window.__toucanForceProxyOriginTo,c=b.match(ra);if(c)b=new P(c[1],c[2],c[4]?c[4]-0:h);else throw v("invalid origin: %s",b),Error();}else if(window.__toucanForceProxyOriginToThisOrigin)b=M(window.location.href+"").a;else{if(c=b.host().match(/^([\w\-\.]+\.)?amazon\.([\w\.]+)$/)){if("https"==b.scheme()){b=new P("https","api-cdn.amazon."+c[2],h);break a}v("no proxy origin; unsupported non-https target origin for amazon: %s",b)}v("no proxy origin; unsupported target origin: %s",
b);throw Error();}c=b;if(!S){var d=window.postMessage?"pm":"fr";window.__toucanForceTransport&&(d=window.__toucanForceTransport);if("pm"==d)d=new U;else if("fr"==d)d=new V;else throw v("unknown transport: %s",d),Error();S=d;S.b(c,function(a,b){var c=R[a];c&&c.b(b)})}var d=b,e=S,c=d.host().replace(/[^a-z0-9]/ig,"_");d.port()&&(c+="_"+d.port());var c=w("amazon-proxy-%s-%s",d.scheme(),c),p=document.getElementById(c);p||(p=document.createElement("iframe"),p.setAttribute("id",c),p.setAttribute("name",
c),p.setAttribute("src",ua(d,e).toString()),ba("amazon-proxy-root").appendChild(p));d=sa(16);R[d]||(R[d]=new ca);R[d].a.push({q:a,u:i});a=b;b={uri:va().toString(),proxy:c,topic:d,version:"1"};return Q(a,"/sdk/2014-02-12-k8c52wxs/topic.html",b,"")}function va(){return qa(M(window.location.href+""),{f:"",g:""})}function ua(a,b){var c={uri:va().toString(),tr:b.name()};return Q(a,"/sdk/2014-02-12-k8c52wxs/proxy.html",{version:"1"},c)}var wa=/^ABMNZNXDC;([\w\d\_\-]+);(.+)$/;
function xa(a){var b=a.match(wa);if(b){a={};a.id=b[1];for(var c={},b=b[2].split("&"),d=0;d<b.length;d++){var e=b[d].split("=");2==e.length&&(c[e[0]]=decodeURIComponent(e[1].replace(/\+/g," ")))}a.data=c;return a}return h}function U(){this.a=f}U.prototype.name=function(){return"pm"};
U.prototype.b=function(a,b){if(this.a===f){var c=this.a=new ca,d=function(a){var b;(b=xa(a.data))&&c.b(a.origin,b.id,b.data)};window.addEventListener?window.addEventListener("message",d,i):window.attachEvent?window.attachEvent("onmessage",d):v("cannot attach message event")}var e=a.toString();this.a.a.push({q:function(a,c,d){a!=e||b(c,d)},u:g})};U.prototype.send=function(a,b,c){var d=a.a;setTimeout(function(){window.parent.postMessage(w("%s;%s;%s","ABMNZNXDC",b,K(c)),d.toString())},1)};
function V(){}V.prototype.name=function(){return"fr"};V.prototype.b=function(a,b){window.__toucanInvokeFragment=function(a,d){b(a,d)}};V.prototype.send=function(a,b,c){var d=a.f();(d=d||"")&&(d+="&");d=d+"ABMNZNXDC"+("="+sa(8));a=qa(a,{f:d,g:w("%s;%s;%s","ABMNZNXDC",b,K(c))});b=document.createElement("iframe");b.setAttribute("src",a.toString());document.body.appendChild(b)};var ya=window.location.href.split("#")[1]||"";
if(ya){var za=xa(ya);za&&(document.documentElement.style.display="none","function"==typeof window.parent.parent.__toucanInvokeFragment&&window.parent.parent.__toucanInvokeFragment(za.id,za.data))}function Aa(){W!=h&&("function"==typeof W.close&&W.close(),W=h)}function Ba(a,b,c){b={client_id:X,redirect_uri:b,response_type:a.response_type,scope:a.scope.toString()};Ca&&(b.sandbox=g);a.state&&(b.state=a.state);c&&(b.exac=c);return Q(T,"/ap/oa",b)}
function Da(a,b,c){Y=i;b.access_token!=h?(c=parseInt(b.expires_in,10),c=60>=c?c:c-Math.min(Math.floor(0.1*c),300),r.B(b,c),s.w()?q.d.setItem("amazon_Login_accessToken",b.access_token,c):q.d.removeItem("amazon_Login_accessToken")):c&&q.d.removeItem("amazon_Login_accessToken");a.t(b);a=Ea;Ea=[];for(b=0;b<a.length;b++)Fa(a[b])}
function Ga(a,b){var b=b+(-1==b.indexOf("?")?"?":"&"),b=b+K(a),c=M(b),d=M(window.location.href+"");"https"!=c.scheme()&&!pa(c)&&v("attempted redirect to %s but scheme is not HTTPS",b);c.host()!=d.host()&&v("attempted redirect to %s but it does not match current host %s",c.host(),d.host());c=b;Aa();window.location.href=c}
function Ha(a){var b=this;this.b=a;this.l=h;this.e=[];this.c=h;this.a={status:h,onComplete:function(a){"string"!=typeof a&&"function"!=typeof a&&v("onComplete expects handler parameter to be a function or a string");var d=b.a.status==Z.o;"string"==typeof a?d?Ga(b.c,a):b.l=a:"function"==typeof a&&(d?setTimeout(function(){a(b.a)},0):b.e.push(a));return b.a}}}
function Fa(a){var b=a.b,c=h;if(b.interactive==$.ALWAYS)r.k();else{var d=h;s.w()&&(d=q.d.getItem("amazon_Login_accessToken"));if(c=r.C())"token"==b.response_type&&b.scope.add(c.scope),d?d!=c.access_token&&(r.k(),c=h):d=c.access_token;var e;if(c&&c.scope.contains(b.scope)&&"token"==b.response_type)e={access_token:c.access_token,token_type:"bearer",expires_in:Math.floor((c.expiration_date-(new Date).getTime())/1E3),scope:c.scope.toString()};else if(b.interactive==$.NEVER){if(Y){Ea.push(a);a.m(Z.A);
return}if(d){b=d;Y=g;var p=ba("amazon-client-credentials-root"),c=ba("amazon-client-credentials-root"),t=sa(16),d=document.createElement("iframe");d.setAttribute("name",t);c.appendChild(d);0==document.getElementsByName(t).length&&(c.removeChild(d),d=document.createElement('<iframe name="'+t+'"/>'),c.appendChild(d));d.setAttribute("id",t);var l=document.createElement("form");p.appendChild(l);l.setAttribute("method","POST");l.setAttribute("target",t);d=ta(function(b){p.removeChild(l);var c=document.getElementById(t);
c!=h&&c.parentNode!=h&&c.parentNode.removeChild(c);b==h&&(b={error:"server_error",description:"Server error."});Da(a,b,i)});c=a.b;b={client_id:X,exac:b,grant_type:"client_credentials",redirect_uri:d,response_type:c.response_type,scope:c.scope};c.state!=h&&(b.state=c.state);l.setAttribute("action",Q(T,"/ap/oa",b).toString());l.submit();return}e={error:"invalid_grant",error_description:"invalid grant"}}if(e){setTimeout(function(){a.t(e)},0);return}}b=d;Y=g;c=ta(function(b){Aa();Da(a,b,g)});b=Ba(a.b,
c,b);c=(window.screenX!==f?window.screenX:window.screenLeft)+Math.floor(((window.outerWidth!==f?window.outerWidth:document.documentElement.clientWidth)-800)/2);d=(window.screenY!==f?window.screenY:window.screenTop)+Math.floor(((window.outerHeight!==f?window.outerHeight:document.documentElement.clientHeight)-540)/2);c=w("left=%s,top=%s,width=%s,height=%s,location=1",0>c?0:c,0>d?0:d,800,540);W=window.open(b.toString(),"amazonloginpopup",c)}s={};
var $={ALWAYS:"always",h:"auto",NEVER:"never"},W=h,Y=i,Ea=[],Z={A:"queued",z:"in_progress",o:"complete"},X=f;s.r=function(){return X};s.G=function(a){a.match(/^[\w\-\.]+$/)||v("invalid client ID: %s",a);X=a};var Ia="www.amazon.com",T=new P("https",Ia,h);s.s=function(){return Ia};var Ca=i;s.H=function(a){"number"==typeof a&&(a=!!a);x("sandboxMode",a,"boolean");Ca=a};
s.n=function(a){var b=a.match(/^((http|https):\/\/)?([a-z0-9\-\.]+)(:(\d+))?\/?$/i);b||v("invalid domain: %s",a);var c=b[2]?b[2].toLowerCase():"https";"https"!=c&&v("invalid domain: %s; scheme must be https");var d=b[3];d.match(/^amazon\.[a-z\.]+$/)&&(d="www."+d);b=b[5];Ia=a;T=new P(c,d,b)};s.D=function(){return T};var Ja=i;s.w=function(){return Ja};s.I=function(a){a==h?v("missing useCookie"):"number"==typeof a?a=!!a:"boolean"!=typeof a&&v("expected useCookie to be a boolean");Ja=a};
Ha.prototype.t=function(a){this.c=a;aa(this.a,a);this.m(Z.o);for(a=0;a<this.e.length;a++)this.e[a](this.a);this.l!=h&&Ga(this.c,this.l)};Ha.prototype.m=function(a){this.a.status=a};
s.p=function(a,b){2>arguments.length&&v("authorize expects two arguments (options, next)");a&&"object"!=typeof a&&v("authorize expects options parameter to be an object");b!=h&&("function"!=typeof b&&"string"!=typeof b)&&v("authorize expects next parameter to be a function or a string");var c=aa({interactive:$.h,popup:g,response_type:"token",state:f,scope:f},a||{});x("options.response_type",c.response_type,"string");c.scope||v("missing options.scope");c.scope.constructor!==Array&&"string"!=typeof c.scope&&
v("expected options.scope to be a string or array");c.scope=new n(c.scope);c.interactive==h?c.interactive=$.h:c.interactive!=$.h&&(c.interactive!=$.ALWAYS&&c.interactive!=$.NEVER)&&v("expected options.scope to be one of '"+$.h+"', '"+$.ALWAYS+"', or '"+$.NEVER+"'");var a=c,d=new Ha(a),c=d.a;d.m(Z.z);if(b!=h)c.onComplete(b);a.popup?Fa(d):("string"!=typeof b&&v("next must be redirect URI if !options.popup"),d=Ba(a,M(b+""),h).toString(),Aa(),window.location.href=d);return c};s.F=function(){r.k();q.d.removeItem("amazon_Login_accessToken")};
function Ka(a,b){var c;try{c=da(a)}catch(d){c=h}if(c&&c.Error){var e={success:i};e.error=w("%s: %s",c.Error.Code||"UnknownError",c.Error.Message||"An unknown error occurred");b(e)}else c&&c.Profile?(e={success:g},e.profile=c.Profile,b(e)):(e={success:i,error:"UnknownError: Incomprehensible response from profile endpoint"},b(e))}
u={v:function(a,b){if(b==h&&"function"==typeof a)b=a,s.p({scope:"profile"},function(a){a.error==h?u.v(a.access_token,b):b({success:i,error:a.error})});else if(x("accessToken",a,"string"),x("callback",b,"function"),window.XMLHttpRequest&&"withCredentials"in new window.XMLHttpRequest||"undefined"!==typeof window.XDomainRequest){var c=Q(s.D(),"/ap/user/profile",{access_token:a},""),d;if(window.XDomainRequest)d=new window.XDomainRequest,d.onload=function(){Ka(d.responseText,b)};else{var e=i;d=new window.XMLHttpRequest;
d.onreadystatechange=function(){e||4!=d.readyState||(e=g,Ka(d.responseText,b))}}d.open("GET",c,g);d.send()}else b({success:i,error:"UnsupportedOperation: Cannot retrieve profile in this browser"})}};window.amazon=window.amazon||{};window.amazon.Login=window.amazon.Login||{};window.amazon.Login.getClientId=function(){return s.r()};window.amazon.Login.setClientId=function(a){return s.G(a)};window.amazon.Login.setDomain=function(a){return s.n(a)};window.amazon.Login.setSandboxMode=function(a){return s.H(a)};
window.amazon.Login.setSiteDomain=function(a){return q.n(a)};window.amazon.Login.setUseCookie=function(a){return s.I(a)};window.amazon.Login.authorize=function(a,b){return s.p(a,b)};window.amazon.Login.logout=function(){return s.F()};window.amazon.Login.retrieveProfile=function(a,b){return u.v(a,b)};if("function"==typeof window.onAmazonLoginReady)window.onAmazonLoginReady();

})();
}
